name: emacs-lisp / main

on:
  push:
    branches: [master, main]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-22.04

    steps:
      - uses: purcell/setup-emacs@c851e5408f2d2f657fa80375bbe3fb35029aa488
        with:
          version: 28.2

      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.0.0

      - name: Run exercism/emacs-lisp ci (runs tests) for all exercises
        run: |
          bash bin/stub-check
          bash bin/test-examples
